spring.application.name=Registation_Service
server.port = 2005
spring.datasource.url = jdbc:mysql://localhost:3306/parkingmanagementsystem?createDatabaseIfNotExist=true
spring.datasoure.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.username =root
spring.datasource.password =Bangalore@1010
spring.jpa.hibernate.ddl-auto =update
spring.jpa.show-sql =true
